#!/bin/bash

NS_LIBRARY_PATH="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [[ -r '/etc/profile' ]]; then
  source '/etc/profile'
fi

while read -r ns_tempvar; do
  if [[ -r "${ns_tempvar}" ]]; then
    source "${ns_tempvar}"
    # only source the the first one found
    break
  fi
done <<EOF
/etc/bash.bashrc
/etc/bash/bashrc
/etc/bashrc
EOF

# Add directories to path
while read -r ns_tempvar; do
  # if it exists and isn't already in PATH
  if [[ -d "${ns_tempvar}" && ! "${PATH}" =~ (^|:)${ns_tempvar}/?(:|$) ]]; then
    export PATH="${ns_tempvar}:${PATH}"
  fi
  # in reverse order of priority; the last entry will come first
done <<EOF
/opt/bin
/opt/sbin
/bin
/sbin
/usr/bin
/usr/sbin
/opt/local/bin
/opt/local/sbin
/usr/local/bin
/usr/local/sbin
EOF

# Add home bin, pipx .local/bin, and .bash/bin
export PATH="${HOME}/bin:${HOME}/.local/bin:${HOME}/.bash/bin:${PATH}"
export LD_LIBRARY_PATH="${HOME}/lib:${LD_LIBRARY_PATH}"

# Determine if in a chroot
NS_CHROOT="${debian_chroot:-}"
if [[ -z "${NS_CHROOT}" && -r /etc/debian_chroot ]]; then
  NS_CHROOT="$(</etc/debian_chroot)"
fi

# Source local environment scripts
for ns_tempvar in "${NS_LIBRARY_PATH}/local/environment.d"/*; do
  if [[ -r "${ns_tempvar}" ]]; then
    source "${ns_tempvar}"
  fi
done

# Less variable pollution
unset ns_tempvar
