#!/bin/bash

NX_LIBRARY_PATH="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [[ -r '/etc/profile' ]]; then
  source '/etc/profile'
fi

while read -r nx_tempvar; do
  if [[ -r "${nx_tempvar}" ]]; then
    source "${nx_tempvar}"
    # only source the the first one found
    break
  fi
done <<EOF
/etc/bash.bashrc
/etc/bash/bashrc
/etc/bashrc
EOF

# Add directories to path
while read -r nx_tempvar; do
  # if it exists and isn't already in PATH
  if [[ -d "${nx_tempvar}" && ! "${PATH}" =~ (^|:)${nx_tempvar}/?(:|$) ]]; then
    export PATH="${nx_tempvar}:${PATH}"
  fi
  # in reverse order of priority; the last entry will come first
done <<EOF
/opt/bin
/opt/sbin
/bin
/sbin
/usr/bin
/usr/sbin
/opt/local/bin
/opt/local/sbin
/usr/local/bin
/usr/local/sbin
EOF

# Add home locations even if they don't exist
export PATH="${HOME}/bin:${PATH}"
export LD_LIBRARY_PATH="${HOME}/lib:${LD_LIBRARY_PATH}"

# Determine if in a chroot
NX_CHROOT="${debian_chroot:-}"
if [[ -z "${NX_CHROOT}" && -r /etc/debian_chroot ]]; then
  NX_CHROOT="$(</etc/debian_chroot)"
fi

# Source local environment scripts
for nx_tempvar in "${NX_LIBRARY_PATH}/local/environment.d"/*; do
  if [[ -r "${nx_tempvar}" ]]; then
    source "${nx_tempvar}"
  fi
done

# Less variable pollution
unset nx_tempvar
