#!/bin/env bash

nx_dealias nx_cdiff_enabled
nx_cdiff_enabled()
{
    # force if output is to terminal
    if [ "$CDIFF_FORCE_COLOR" == 1 ] || [ -t 1 ]; then
        return 0
    else
        return 1
    fi
}
nx_dealias nx_diff_wrapper
nx_diff_wrapper()
{
    if nx_cdiff_enabled; then
        local applist='colordiff diff'
    else
        local applist='diff'
    fi
    for app in $applist
    do
        local diffapp="$(nx_path_search $app)";
        if [ -x "$diffapp" ]; then
            "$diffapp" "$@"
            return $?
        fi
    done
    echo 'ERROR: diff command not found!' >&2
    return 1
}	
