#!/bin/env bash

nx_diff_wrapper() {
    # wrap diff to use colordiff if it's available
    if [ "$CDIFF_FORCE_COLOR" == 1 ] || [ -t 1 ]; then
        local applist='colordiff diff'
    else
        local applist='diff'
    fi
    for app in $applist
    do
        local diffapp="$(nx_path_search $app)";
        if [ -x "$diffapp" ]; then
            "$diffapp" "$@"
            return $?
        fi
    done
    echo 'ERROR: diff command not found!' >&2
    return 1
}	
