#!/bin/bash

ns_diff_wrapper() {
  # wrap diff to use colordiff if it's available
  local applist
  if [[ "${CDIFF_FORCE_COLOR}" -eq 1 || -t 1 ]]; then
    applist='colordiff diff'
  else
    applist='diff'
  fi
  for app in ${applist}; do
    local diffapp
    diffapp="$(ns_path_search "${app}")"
    if [[ -x "${diffapp}" ]]; then
      "${diffapp}" "$@"
      return $?
    fi
  done
  ns_error 'diff command not found'
  return 1
}
