#!/bin/env bash

nx_library tput stringops

nx_bash_prompt() {
  local ESTAT DIVCHR
  # enclosing all escape sequences with \[ \] so it doesn't contribute to the line's character count
  ESTAT="\$(ECODE=\$?; [ \$ECODE -eq 0 ] && echo '\[$(nx_tput_term_fg 4)\]' || echo '\[$(nx_tput_term_fg 1)\]'; exit \$ECODE)"

  # Root prompt ends with #, non-root ends with $
  DIVCHR="\$(ECODE=\$?; [ \"\$EUID\" -eq 0 ] && echo '#' || echo '\$'; exit \$ECODE)"

  # actual prompt
  # [user@host dir]#
  if [[ "$(nx_tput_colors)" -ge 8 ]]; then
    # there's at least 8 colors
    echo "\[$(nx_tput_term_normal)\]${NX_CHROOT:+($NX_CHROOT)}${ESTAT}\[$(nx_tput_term_bold)\][\[$(nx_tput_term_normal)$(nx_tput_term_fg 2)\]\u@\h \[$(nx_tput_term_fg 6)$(nx_tput_term_bold)\]\w${ESTAT}]${DIVCHR}\[$(nx_tput_term_normal)\] "
  else
    echo "${NX_CHROOT:+($NX_CHROOT)}[\u@\h \w]${DIVCHR} "
  fi
}
nx_set_bash_prompt() {
  unset PROMPT_COMMAND
  PS1="$(nx_bash_prompt)"
}
nx_set_titles_with_prompt() {
  case "$TERM" in
    # If this is an xterm set the title to user@host:dir
    xterm* | rxvt*)
      PS1="\[\e]0;${NX_CHROOT:+($NX_CHROOT)}\u@\h: \w\a\]$PS1"
      ;;
  esac
}
