#!/bin/bash

ns_ssh_agent() {
  if [[ -z "${SSH_AUTH_SOCK}" ]] || [[ -z "${SSH_AGENT_PID}" ]]; then
    if ns_path_search keychain &>/dev/null; then
      eval "$(keychain -q --nogui --noask --eval --agents ssh)"
    elif ns_path_search ssh-agent &>/dev/null; then
      eval "$(ssh-agent -s)"
    fi
  fi
}

ns_select_ssh_id() {
    if [[ $# -ne 1 ]]; then
      ns_error "Must specify exactly one ssh id, but $# were specified."
      return 1
    fi
    key_id="${1}"
    key_root_path="${HOME}/.ssh/id_"
    key_path="${key_root_path}${key_id}"
    selected_key_path="${key_root_path}default"
    if [[ ! -e "${key_path}" ]]; then
      ns_error "No such ssh key: ${key_path}"
      return 1
    fi
    # remove default keys
    for default_key_path in "${selected_key_path}" "${selected_key_path}.pub"; do
      if [[ -L "${default_key_path}" ]]; then
        unlink "${default_key_path}"
      elif [[ -e "${default_key_path}" ]]; then
        ns_error "Selected ssh key exists and is not a symlink; aborting due to file: ${default_key_path}"
        return 1
      fi
    done
    ln -s "id_${key_id}" "${selected_key_path}"
    if [[ -e "${key_path}.pub" ]]; then
      ln -s "id_${key_id}.pub" "${selected_key_path}.pub"
    fi
}
