#!/bin/env bash

# if the framework is sourced
if type -p NX_FRAMEWORK_SOURCED &>/dev/null; then

	nx_install_nacitar_ssh_key()
	{
		nacitar_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkFZ6munFhq/rWwWhrTz+eWMzx3+nrg6YqJQzUff3n+pt7djHSBNEMwTC3cMQvsosdY6XW5jGNwgzmQEGfiSm4j646sm7pD+f7jm4Ciim4guvhsfbWl+wnsLXQgUhIN7yxl8swGUsIGBoe+UAnvGIbNSSQX8R4m1RuVLYbd325mznHBN42zuLM272mKo/2zOr/kykE5C8JdrfYMjmc32s7bfjbAjqkXwsDE/UXmy2+51w5dFSNwCmcWAcRxk+GI0KKf57vvOm7MUyhu/Qzvt9nIgzgw17swoV+INafZqd5uojfp6aTx3nnF2Cgc+KxYLGctbY23zrtYvl8/7bAAaKX"
		nacitar_name="nacitar.sevaht"
		ssh_dir="$HOME/.ssh"
		auth_keys="$ssh_dir/authorized_keys"

		# Make ssh dir
		if ! [ -d "$ssh_dir" ]; then
			mkdir "$ssh_dir"
		fi

		# Make auth keys
		if ! [ -e "$auth_keys" ]; then
			touch "$auth_keys"
			chmod 644 "$auth_keys"
		fi

		# If not added, append it
		if ! grep "$nacitar_key" "$auth_keys" &>/dev/null; then
			echo "$nacitar_key $nacitar_name" >> "$auth_keys"
		fi
	}

fi
