#!/bin/env bash

# if the framework is sourced
if type -p NX_FRAMEWORK_SOURCED &>/dev/null; then

	nx_dealias nx_stringize_escape
	nx_stringize_escape()
	{
		echo "${@//$'\e'/\\e}"
	}

	# <dir> <desired max length>
	# 0 for max compression, -1 for home-replace only
	nx_dealias nx_abbreviate_dir
	nx_abbreviate_dir() {
		local IFS=/ c=1 n d r p s
		p=( ${1/#$HOME/\~} )
		if [ "$2" != "-1" ]; then
			r=${p[*]}
			s=${#r}
			while ((s>$2&&c<${#p[*]}-1))
			do
				d=${p[c]}
				n=1;[[ $d = .* ]]&&n=2
				((s-=${#d}-n))
				p[c++]=${d:0:n}
			done
		fi
		if [ "${#p[@]}" == "1" ] && [ -z "${p[0]}" ]; then
			echo "/"
		else
			echo "${p[*]}"
		fi
	}

fi
