#!/bin/bash

ns_python_version() {
    if [[ $# -ne 1 ]]; then
      ns_error "Must pass a python binary name or path."
      return 1
    fi
    if type -p "${1}" &>/dev/null; then
        "${1}" -c 'import sys; print(sys.version)' 2>/dev/null
    else
        return 1
    fi
}

ns_system_update() {
    local python py_version 
    for python in python3 python ''; do
        if [[ -n "${python}" ]] \
                && type -p "${python}" &>/dev/null \
                && "${python}" -m pipx --version &>/dev/null; then
            py_version="$(ns_python_version "${python}")"
            break
        fi
    done

    if type -p yay &>/dev/null; then
        yay --noconfirm --sudoloop
    elif type -p pacman &>/dev/null; then
        sudo pacman -Syu --noconfirm
    elif type -p apt-get &>/dev/null; then
        sudo apt-get update -y
        sudo apt-get dist-upgrade -y
    elif type -p dnf &>/dev/null; then
        sudo dnf upgrade --refresh -y
    elif type -p yum &>/dev/null; then
        sudo yum clean all
        sudo yum update -y
    else
        &>2 echo "ERROR: couldn't identify package manager."
        exit 1
    fi

    if [ -n "${python}" ]; then
        if [[ "${py_version}" != "$(ns_python_version "${python}")" ]]; then
            "${python}" -m pipx reinstall-all
        fi
        "${python}" -m pipx upgrade-all
    fi
}
