#!/bin/env bash

nx_in_tmux_session() {
    [ -n "$TMUX" ]
}
nx_get_uid_from_pid() {
    local status="/proc/$1/status"
    if nx_has_sed && [ -r "$status" ]; then
        sed -n 's/^Uid:[[:space:]]*\([[:digit:]]\+\).*$/\1/p' "$status"
    fi
}
nx_set_tmux_window_name() {
    printf "\ek$@\e\\"
}
nx_set_tmux_pane_title() {
    printf "\e]2;$@\e\\"
}
nx_set_tmux_titles() {
    nx_set_tmux_window_name "$@"
    nx_set_tmux_pane_title "$@"
}
nx_get_tmux_pid() {
    local values
    IFS=, values=( $TMUX )
    echo "${values[1]}"
}
nx_get_tmux_uid() {
    echo "$(nx_get_uid_from_pid "$(nx_get_tmux_pid)")"
}
